version: '3'

services:
  backend-db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    networks:
      - backend-network
    volumes:
      - backend-db:/var/lib/postgresql/data
    env_file:
      - ./db.env
  next-app:
    container_name: next-server
    restart: always
    build:
      dockerfile: ./apps/student/Dockerfile
      context: .
    ports:
      - 3000:3000
    networks:
      - backend-network
      - proxy-network
  nginx:
    build: ./nginx
    ports:
      - 80:80
    networks:
      - proxy-network
networks:
  backend-network: 
  proxy-network:
volumes:
  backend-db:
