version: '3'

services:
  backend-db:
    image: postgres:15
    ports:
      - 5433:5432
    networks:
      - backend-network
      - db-network
    volumes:
      - backend-db:/var/lib/postgresql/data
    env_file:
      - ./db.env
  next-app:
    container_name: next-server
    build:
      context: .
    ports:
      - 3000:3000
    networks:
      - backend-network
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    networks:
      - db-network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=p@ssw0rd
networks:
  backend-network: 
  db-network:
volumes:
  backend-db: