version: '3'

tasks:
  plan-apply:
    cmds:
      - terraform init
      - terraform plan -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" 
    silent: true
  apply:
    cmds:
      - terraform init
      - terraform apply -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" --auto-approve --parallelism=1
  plan-destroy:
    cmds:
      - terraform init
      - terraform plan -destroy -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars"
    silent: true
  destroy:
    cmds:
      - terraform init
      - terraform destroy -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" --auto-approve --parallelism=1