version: '3'

tasks:
  plan-apply:
    dir: ./terraform/postgres-manager
    desc: Terraform plan for apply
    cmds:
      - terraform init
      - terraform plan -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" 
    silent: true
  apply:
    dir: ./terraform/postgres-manager
    desc: Terraform apply
    cmds:
      - terraform init
      - terraform apply -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" --auto-approve --parallelism=1
      - terraform output -json user_password | jq . > ../../build/postgres-management.output.json
  plan-destroy:
    dir: ./terraform/postgres-manager
    desc: Terraform plan for destroy
    cmds:
      - terraform init
      - terraform plan -destroy -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars"
    silent: true
  destroy:
    dir: ./terraform/postgres-manager
    desc: Terraform destroy
    cmds:
      - terraform init
      - terraform destroy -var-file="./configs/host.tfvars" -var-file="./configs/config.tfvars" --auto-approve --parallelism=1