version: '3'

tasks:
  migrate:
    desc: Prisma migrate db & generate @prisma/client
    cmds:
      - npx prisma migrate dev
      - npx prisma generate
      - yarn add @prisma/client@latest
    silent: true
    internal: true