import SystemTimeline from '@component/SystemTimeline'
import { Grid, Typography } from '@mui/material'
import Head from 'next/head'

const timeline = [
  { 
    evtName: 'register',
    date: new Date()
  }
]

export default function Home() {
  return (
    <div >
      <Head>
        <title>BestMatch</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Typography align='center' variant='h2' sx={{mt: 3}} >
          Welcome to BestMatch!
        </Typography>
        <Grid container spacing={2} sx={{ mt: 3}}>
          <Grid item xs={12} md={4}>
            <SystemTimeline timeline={timeline} />
          </Grid>
          <Grid item xs={6} md={8} sx={{backgroundColor: 'green'}}>
          </Grid>
        </Grid>
      </main>
    </div>
  )
}
